name: ci/cd

on:
  push:
    paths-ignore:
    - 'examples/**'
  pull_request:

jobs:
  all-in-one:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Install dotnet-releaser
      run: dotnet tool install -g dotnet-releaser
    - name: Run dotnet-releaser
      shell: bash
      run: |
        dotnet user-secrets set "PineconeApiKey" "${{secrets.PINECONE_API_KEY}}" --project test
        dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml